/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ClassificationPolicy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:54:18.445Z")
public class ClassificationPolicy {
  @SerializedName("policyId")
  private String policyId = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("policyHash")
  private String policyHash = null;

  public ClassificationPolicy policyId(String policyId) {
    this.policyId = policyId;
    return this;
  }

   /**
   * Get policyId
   * @return policyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPolicyId() {
    return policyId;
  }

  public void setPolicyId(String policyId) {
    this.policyId = policyId;
  }

  public ClassificationPolicy tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public ClassificationPolicy addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public ClassificationPolicy policyHash(String policyHash) {
    this.policyHash = policyHash;
    return this;
  }

   /**
   * A hash of the policy body and any associated custom patterns.  This can be used to track significant changes to the policy that may warrant re-classification of documents.  Note that built-in pattern bodies are NOT included in the hash, as they are not expected to change significantly over time.
   * @return policyHash
  **/
  @ApiModelProperty(example = "null", value = "A hash of the policy body and any associated custom patterns.  This can be used to track significant changes to the policy that may warrant re-classification of documents.  Note that built-in pattern bodies are NOT included in the hash, as they are not expected to change significantly over time.")
  public String getPolicyHash() {
    return policyHash;
  }

  public void setPolicyHash(String policyHash) {
    this.policyHash = policyHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationPolicy classificationPolicy = (ClassificationPolicy) o;
    return Objects.equals(this.policyId, classificationPolicy.policyId) &&
        Objects.equals(this.tags, classificationPolicy.tags) &&
        Objects.equals(this.policyHash, classificationPolicy.policyHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyId, tags, policyHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationPolicy {\n");
    
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    policyHash: ").append(toIndentedString(policyHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

