/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RuleMatch;
import io.swagger.client.model.Tag;
import java.util.ArrayList;
import java.util.List;

/**
 * The result from classification of a document against a single policy.  Includes a suggested tag as well as the policy id and name.  May also include details of the matching content, if enabled.
 */
@ApiModel(description = "The result from classification of a document against a single policy.  Includes a suggested tag as well as the policy id and name.  May also include details of the matching content, if enabled.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T22:54:18.445Z")
public class ClassificationResult {
  @SerializedName("policyId")
  private String policyId = null;

  @SerializedName("policyName")
  private String policyName = null;

  @SerializedName("tags")
  private List<Tag> tags = new ArrayList<Tag>();

  @SerializedName("ruleMatches")
  private List<RuleMatch> ruleMatches = new ArrayList<RuleMatch>();

  public ClassificationResult policyId(String policyId) {
    this.policyId = policyId;
    return this;
  }

   /**
   * The identity of the policy that was matched against.
   * @return policyId
  **/
  @ApiModelProperty(example = "null", value = "The identity of the policy that was matched against.")
  public String getPolicyId() {
    return policyId;
  }

  public void setPolicyId(String policyId) {
    this.policyId = policyId;
  }

  public ClassificationResult policyName(String policyName) {
    this.policyName = policyName;
    return this;
  }

   /**
   * The name of the policy that was matched against.
   * @return policyName
  **/
  @ApiModelProperty(example = "null", value = "The name of the policy that was matched against.")
  public String getPolicyName() {
    return policyName;
  }

  public void setPolicyName(String policyName) {
    this.policyName = policyName;
  }

  public ClassificationResult tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public ClassificationResult addTagsItem(Tag tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Suggested tags to represent the policy match.  A client may want to attach the tags to the original document as a way of recording the classification result.
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "Suggested tags to represent the policy match.  A client may want to attach the tags to the original document as a way of recording the classification result.")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }

  public ClassificationResult ruleMatches(List<RuleMatch> ruleMatches) {
    this.ruleMatches = ruleMatches;
    return this;
  }

  public ClassificationResult addRuleMatchesItem(RuleMatch ruleMatchesItem) {
    this.ruleMatches.add(ruleMatchesItem);
    return this;
  }

   /**
   * Collection of rule matches giving details of how the classification was determined. Optional, so may not be populated.
   * @return ruleMatches
  **/
  @ApiModelProperty(example = "null", value = "Collection of rule matches giving details of how the classification was determined. Optional, so may not be populated.")
  public List<RuleMatch> getRuleMatches() {
    return ruleMatches;
  }

  public void setRuleMatches(List<RuleMatch> ruleMatches) {
    this.ruleMatches = ruleMatches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationResult classificationResult = (ClassificationResult) o;
    return Objects.equals(this.policyId, classificationResult.policyId) &&
        Objects.equals(this.policyName, classificationResult.policyName) &&
        Objects.equals(this.tags, classificationResult.tags) &&
        Objects.equals(this.ruleMatches, classificationResult.ruleMatches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyId, policyName, tags, ruleMatches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationResult {\n");
    
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    ruleMatches: ").append(toIndentedString(ruleMatches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

