/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ClassificationResultCollection;
import io.swagger.client.model.ErrorResponse;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VeritasInformationClassifierVICApi
 */
@Ignore
public class VeritasInformationClassifierVICApiTest {

    private final VeritasInformationClassifierVICApi api = new VeritasInformationClassifierVICApi();

    
    /**
     * Determine a document&#39;s classification(s)
     *
     * Classify a document using the specified policies or the tenant&#39;s default policies.   The document can be supplied by value (a stream of bytes) or by reference (a file path).  The document is automatically converted to text where required.   The classification results include the policies matched and suggested classification &#39;tags&#39; that the caller may associate with the content.  Extra information can optionally be returned giving more details about the content that triggered the classification - this reduces performance but is useful for diagnostics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void classifyTest() throws ApiException {
        String tenantId = null;
        List<String> policyId = null;
        String policy = null;
        List<String> metadata = null;
        String metadataFile = null;
        String documentName = null;
        Boolean includeMatches = null;
        Integer maxContentMatchesPerRule = null;
        Boolean skipTextExtraction = null;
        Boolean skipWhitespaceCollapse = null;
        File file = null;
        ClassificationResultCollection response = api.classify(tenantId, policyId, policy, metadata, metadataFile, documentName, includeMatches, maxContentMatchesPerRule, skipTextExtraction, skipWhitespaceCollapse, file);

        // TODO: test validations
    }
    
}
